--User table
CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL NOT NULL,
    name VARCHAR(50),
    token VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (user_id)
);
--Food table
CREATE TABLE IF NOT EXISTS food (
    food_id SERIAL NOT NULL,
    name VARCHAR(100) NOT NULL,
    kcal INTEGER,
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_FOOD PRIMARY KEY (food_id),
    CONSTRAINT CHECK_FOOD_KCAL_POSITIVE CHECK (
        kcal IS NULL
        OR kcal >= 0
    )
);
--Recipe table
CREATE TABLE IF NOT EXISTS recipes (
    recipe_id SERIAL NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id INTEGER NOT NULL,
    is_public BOOLEAN DEFAULT FALSE NOT NULL,
    servings INTEGER DEFAULT 2 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_RECIPE PRIMARY KEY (recipe_id),
    CONSTRAINT FK_RECIPE_USER FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
--Shopping list
CREATE TABLE IF NOT EXISTS shopping_lists (
    list_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_SHOPPING_LIST PRIMARY KEY (list_id),
    CONSTRAINT FK_SHOPPING_LIST_USER FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
--M to M table Shopping List <-> Food
CREATE TABLE IF NOT EXISTS food_lists (
    food_id INTEGER NOT NULL,
    list_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_FOOD_LIST PRIMARY KEY (food_id, list_id),
    CONSTRAINT FK_FOOD_LIST_FOOD FOREIGN KEY (food_id) REFERENCES food (food_id) ON DELETE CASCADE,
    CONSTRAINT FK_FOOD_LIST_SHOPPING_LIST FOREIGN KEY (list_id) REFERENCES shopping_lists (list_id) ON DELETE CASCADE
);
--M to M table Recipe <-> Food
CREATE TABLE IF NOT EXISTS recipe_foods (
    food_id INTEGER NOT NULL,
    recipe_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    modified_at TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT PK_RECIPE_FOODS PRIMARY KEY (food_id, recipe_id),
    CONSTRAINT FK_RECIPE_FOODS_FOOD FOREIGN KEY (food_id) REFERENCES food (food_id) ON DELETE CASCADE,
    CONSTRAINT FK_RECIPE_FOODS_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE
);
CREATE OR REPLACE FUNCTION set_modified_at() RETURNS TRIGGER AS $$ BEGIN NEW.modified_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER TRG_USER_MODIFIED_AT BEFORE
UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_modified_at();
CREATE TRIGGER TRG_FOOD_MODIFIED_AT BEFORE
UPDATE ON food FOR EACH ROW EXECUTE FUNCTION set_modified_at();
CREATE TRIGGER TRG_RECIPE_MODIFIED_AT BEFORE
UPDATE ON recipes FOR EACH ROW EXECUTE FUNCTION set_modified_at();
CREATE TRIGGER TRG_SHOPPING_LIST_MODIFIED_AT BEFORE
UPDATE ON shopping_lists FOR EACH ROW EXECUTE FUNCTION set_modified_at();
CREATE TRIGGER TRG_FOOD_LIST_MODIFIED_AT BEFORE
UPDATE ON food_lists FOR EACH ROW EXECUTE FUNCTION set_modified_at();
CREATE TRIGGER TRG_RECIPE_FOODS_MODIFIED_AT BEFORE
UPDATE ON recipe_foods FOR EACH ROW EXECUTE FUNCTION set_modified_at();